sdzblog_blog_ajouter:
    path:   /ajouter
    defaults:  { _controller: "SdzBlogBundle:Blog:ajouter" }

sdzblog_blog_modifier:
    path:   /modifier/{id}
    defaults:  { _controller: "SdzBlogBundle:Blog:modifier" }
    requirements:
        id:  \d+

sdzblog_blog_supprimer:
    path:   /supprimer/{id}
    defaults:  { _controller: "SdzBlogBundle:Blog:supprimer" }
    requirements:
        id:  \d+

sdzblog_blog_feed:
    path:   /feed.rss
    defaults:  { _controller: "SdzBlogBundle:Blog:feed" }

sdzblog_blog_voir:
    path:   /{slug}
    defaults:  { _controller: "SdzBlogBundle:Blog:voir" }

sdzblog_commentaire_ajouter:
    path:  /ajouter/{id}/commentaire
    defaults: { _controller: "SdzBlogBundle:Commentaire:ajouter" }
    methods:  POST
    requirements:
        id:      \d+

sdzblog_commentaire_supprimer:
    path:   /supprimer/commentaire/{id}
    defaults:  { _controller: "SdzBlogBundle:Commentaire:supprimer" }
    requirements:
        id:  \d+
