sdzblog_ajouter:
    path:   /ajouter
    defaults:  { _controller: "SdzBlogBundle:Blog:ajouter" }

sdzblog_modifier:
    path:   /modifier/{id}
    defaults:  { _controller: "SdzBlogBundle:Blog:modifier" }
    requirements:
        id:  \d+

sdzblog_supprimer:
    path:   /supprimer/{id}
    defaults:  { _controller: "SdzBlogBundle:Blog:supprimer" }
    requirements:
        id:  \d+

sdzblog_feed:
    path:   /feed.rss
    defaults:  { _controller: "SdzBlogBundle:Blog:feed" }

sdzblog_voir:
    path:   /{slug}
    defaults:  { _controller: "SdzBlogBundle:Blog:voir" }

sdzblog_ajouter_commentaire:
    path:  /ajouter/{id}/commentaire
    defaults: { _controller: "SdzBlogBundle:Blog:ajouterCommentaire" }
    methods:  POST
    requirements:
        id:      \d+

sdzblog_supprimer_commentaire:
    path:   /supprimer/commentaire/{id}
    defaults:  { _controller: "SdzBlogBundle:Blog:supprimerCommentaire" }
    requirements:
        id:  \d+
